version: "3"
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./bootstrap:/bootstrap
      - ./docker/web/database.yml:/bootstrap/config/database.yml
    ports:
      - "3000:3000"
    links:
      - db
